# Generated by Django 5.1.3 on 2024-11-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('streetNumber', models.CharField(max_length=10)),
                ('steetName', models.CharField(max_length=100)),
                ('apartmentNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('zipCode', models.CharField(max_length=10)),
                ('dateOfBirth', models.DateField()),
                ('dateOfRegistration', models.DateField()),
                ('partyAffiliation', models.CharField(max_length=50)),
                ('precinctNumber', models.IntegerField()),
                ('v20State', models.BooleanField(default=False)),
                ('v21Town', models.BooleanField(default=False)),
                ('v21Primary', models.BooleanField(default=False)),
                ('v22General', models.BooleanField(default=False)),
                ('v23Town', models.BooleanField(default=False)),
                ('voterScore', models.IntegerField()),
            ],
        ),
    ]
