# Generated by Django 5.1.3 on 2024-11-14 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='steetName',
            new_name='streetName',
        ),
    ]
