# Generated by Django 5.1.3 on 2024-11-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0002_rename_steetname_voter_streetname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='precinctNumber',
            field=models.CharField(max_length=10),
        ),
    ]
